// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://wikimediafoundation.org/wiki/Terms_of_Use",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/unique-devices/{project}/{accessSite}/{granularity}/{start}/{end}": {
            "get": {
                "description": "Given a wiki page and a date range, returns number of unique devices that visited that page.",
                "produces": [
                    "application/json"
                ],
                "summary": "Number of unique devices.",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en.wikipedia.org",
                        "description": "Domain of a Wikimedia project",
                        "name": "project",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UniqueDevicesResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.UniqueDevices": {
            "type": "object",
            "properties": {
                "access-site": {
                    "type": "string"
                },
                "devices": {
                    "type": "integer"
                },
                "granularity": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "project": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "underestimate": {
                    "type": "integer"
                }
            }
        },
        "main.UniqueDevicesResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.UniqueDevices"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "DRAFT",
	Host:             "localhost:8080",
	BasePath:         "/metrics/unique-devices/",
	Schemes:          []string{"http"},
	Title:            "Wikimedia UniqueDevices API",
	Description:      "*This page is a work in progress.*\n\nUnique Devices is a public API developed and maintained by the Wikimedia Foundation that serves analytical\ndata about number of unique devices of Wikipedia and its sister projects. ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
