basePath: /metrics/unique-devices/
definitions:
  main.UniqueDevices:
    properties:
      access-site:
        type: string
      devices:
        type: integer
      granularity:
        type: string
      offset:
        type: integer
      project:
        type: string
      timestamp:
        type: string
      underestimate:
        type: integer
    type: object
  main.UniqueDevicesResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/main.UniqueDevices'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: "*This page is a work in progress.*\n\nUnique Devices is a public API
    developed and maintained by the Wikimedia Foundation that serves analytical\ndata
    about number of unique devices of Wikipedia and its sister projects. "
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  title: Wikimedia UniqueDevices API
  version: DRAFT
paths:
  /unique-devices/{project}/{accessSite}/{granularity}/{start}/{end}:
    get:
      description: Given a wiki page and a date range, returns number of unique devices
        that visited that page.
      parameters:
      - description: Domain of a Wikimedia project
        example: en.wikipedia.org
        in: path
        name: project
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.UniqueDevicesResponse'
      summary: Number of unique devices.
schemes:
- http
swagger: "2.0"
